apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          args:
            - "--provider=oidc"
            - "--client-id=<YOUR_OKTA_CLIENT_ID>"
            - "--client-secret=<YOUR_OKTA_CLIENT_SECRET>"
            - "--redirect-url=<REDIRECT_URL>"
            - "--email-domain=*"
            - "--cookie-secret=<COOKIE_SECRET>"
          ports:
            - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  ports:
    - port: 80
      targetPort: 4180
  selector:
    app: oauth2-proxy
